# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OmegaMat <- function(n, order, phi, theta) {
    .Call(`_CPDARMABC_OmegaMat`, n, order, phi, theta)
}

simARIMA <- function(mu, sigma2, innovDist, OmegaMat, BetaFlg, W, Beta) {
    .Call(`_CPDARMABC_simARIMA`, mu, sigma2, innovDist, OmegaMat, BetaFlg, W, Beta)
}

YeoJohnson <- function(Y, lambda) {
    .Call(`_CPDARMABC_YeoJohnson`, Y, lambda)
}

invYeoJohnson <- function(X, lambda) {
    .Call(`_CPDARMABC_invYeoJohnson`, X, lambda)
}

distPars <- function(n, model0, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, innovDist, nsim, maxErr) {
    .Call(`_CPDARMABC_distPars`, n, model0, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, innovDist, nsim, maxErr)
}

distLoglikRatio <- function(n, t, distPars0, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, innovDist, nsim, maxErr) {
    .Call(`_CPDARMABC_distLoglikRatio`, n, t, distPars0, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, innovDist, nsim, maxErr)
}

binSeg <- function(Y, alpha, GLRSApprox, minSize, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, maxLev, innovDist, nsim1, nsim2, maxErr, minNonNAN) {
    .Call(`_CPDARMABC_binSeg`, Y, alpha, GLRSApprox, minSize, lowerLambda, upperLambda, breakPoint, BetaFlg, W, Beta, crit, max_p, max_d, max_q, tol, maxIter, maxLev, innovDist, nsim1, nsim2, maxErr, minNonNAN)
}

